FROM node:18-alpine AS builder

WORKDIR /app

# Copia il package.json e installa le dipendenze
COPY package.json package-lock.json ./
RUN npm install -g @angular/cli@16 && npm install

# Copia il resto dell'applicazione
COPY . .

# Costruisce l'applicazione Angular
RUN npm run build -- --output-path=dist

# Usa un server nginx per servire l'app Angular
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
